export const IMMUNE_MULTIPLIER = 0;
export const NEUTRAL_MULTIPLIER = 1;
export const RESISTED_MULTIPLIER = 0.5;
export const DOUBLE_WEAK_MULTIPLIER = 4;
export const SUPER_EFFECTIVE_MULTIPLIER = 2;
export const DOUBLE_RESISTED_MULTIPLIER = 0.25;

export const SUPER_EFFECTIVE_THRESHOLD = SUPER_EFFECTIVE_MULTIPLIER;

export const EFFECTIVENESS_MATRIX_PAGE_SIZE = 500;
